name: Stage-1 Deployment

on:
  workflow_dispatch:
    inputs:
      execute:
        description: 'Execute Stage-1 Deployment'
        required: true
env:
  AWS_REGION: us-west-2

permissions:
    id-token: write
    contents: read

jobs:
  deploy_stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      # - name: Terraform Init
      #   run: terraform init
      # - name: Teeraform Plan
      #   run: terraform plan -out=tfplan
      # - name: Terraform apply
      #   run: terraform apply -auto-approve tfplan
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::264745370841:role/GitHubAction-AssumeRoleWithAction
          role-session-name: Github_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}
      - name: Sts GetCallerIdentity
        run:
          aws sts get-caller-identity
      # Add your stage-1 deployment steps here
      